# Generated by Django 4.2.30 on 2026-04-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(max_length=500)),
                ('pickup_location', models.CharField(max_length=500)),
                ('dropoff_location', models.CharField(max_length=500)),
                ('current_cycle_hours', models.FloatField(default=0)),
                ('start_time', models.DateTimeField()),
                ('sleeper_berth_split', models.CharField(default='7_3', max_length=10)),
                ('trip_summary', models.JSONField(default=dict)),
                ('stops', models.JSONField(default=list)),
                ('daily_logs', models.JSONField(default=list)),
                ('route_geometry', models.JSONField(default=dict)),
                ('current_location_coords', models.JSONField(default=dict)),
                ('pickup_location_coords', models.JSONField(default=dict)),
                ('dropoff_location_coords', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
